/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module multiply_9 (
    input alufn0,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] p
  );
  
  
  
  always @* begin
    p = 16'h0000;
    p = (alufn0 == 1'h0) ? a * b : a / b;
  end
endmodule
