/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_7 (
    input z,
    input v,
    input n,
    input [1:0] alufn,
    output reg [15:0] comp
  );
  
  
  
  always @* begin
    comp = 16'h0000;
    
    case (alufn)
      2'h0: begin
        comp[0+0-:1] = 1'h0;
      end
      2'h1: begin
        comp[0+0-:1] = z;
      end
      2'h2: begin
        comp[0+0-:1] = n ^ v;
      end
      2'h3: begin
        comp[0+0-:1] = z | (n ^ v);
      end
      default: begin
        comp[0+0-:1] = 1'h0;
      end
    endcase
  end
endmodule
